name: Run Colab Notebook

on:
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install nbconvert nbformat
      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute Newsletter_Eclinic.ipynb --output executed_notebook.ipynb
